package ua.hayden.theterminal.ui.theme

import androidx.compose.ui.graphics.Color



val primaryLight = Color(0xFF5C2E2B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE8D0C8)
val onPrimaryContainerLight = Color(0xFF3B1C1A)
val secondaryLight = Color(0xFF7A6F61)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE8E1D9)
val onSecondaryContainerLight = Color(0xFF3F372F)
val tertiaryLight = Color(0xFF4F4A47)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDCDCDC)
val onTertiaryContainerLight = Color(0xFF1F1F1F)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFE4DED8)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFAF8F2)
val onBackgroundLight = Color(0xFF1A1C15)
val surfaceLight = Color(0xFFFAF8F2)
val onSurfaceLight = Color(0xFF1A1C15)
val surfaceVariantLight = Color(0xFFE4E0D4)
val onSurfaceVariantLight = Color(0xFF45483D)
val outlineLight = Color(0xFF75786C)
val outlineVariantLight = Color(0xFFC5C8B9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFFEAEAEA)
val inverseOnSurfaceLight = Color(0xFF1A1C15)
val inversePrimaryLight = primaryLight
val surfaceDimLight = Color(0xFFDADBD0)
val surfaceBrightLight = backgroundLight
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F4E9)
val surfaceContainerLight = Color(0xFFEEEFE3)
val surfaceContainerHighLight = Color(0xFFE8E9DD)
val surfaceContainerHighestLight = Color(0xFFE3E3D8)

val primaryDark = Color(0xFFD9A19E)
val onPrimaryDark = Color(0xFF1A1A1A)
val primaryContainerDark = Color(0xFF753C37)
val onPrimaryContainerDark = Color(0xFFF2D7D5)
val secondaryDark = Color(0xFF7A6F61)
val onSecondaryDark = Color(0xFFFFFFFF)
val secondaryContainerDark = Color(0xFF8F8476)
val onSecondaryContainerDark = Color(0xFFE8E1D9)
val tertiaryDark = Color(0xFF4A4A4A)
val onTertiaryDark = Color(0xFFFFFFFF)
val tertiaryContainerDark = Color(0xFF636363)
val onTertiaryContainerDark = Color(0xFFDCDCDC)
val errorDark = Color(0xFFBA1A1A)
val onErrorDark = Color(0xFFFFFFFF)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1C1B16)
val onBackgroundDark = Color(0xFFEAEAEA)
val surfaceDark = Color(0xFF1C1B16)
val onSurfaceDark = Color(0xFFEAEAEA)
val surfaceVariantDark = Color(0xFF45483D)
val onSurfaceVariantDark = Color(0xFFC5C8B9)
val outlineDark = Color(0xFF8F9285)
val outlineVariantDark = Color(0xFF44473C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEAEAEA)
val inverseOnSurfaceDark = Color(0xFF1A1C15)
val inversePrimaryDark = primaryDark
val surfaceDimDark = Color(0xFF14150F)
val surfaceBrightDark = Color(0xFF34352E)
val surfaceContainerLowestDark = Color(0xFF0E0F09)
val surfaceContainerLowDark = Color(0xFF1E1F18)
val surfaceContainerDark = Color(0xFF23241D)
val surfaceContainerHighDark = Color(0xFF2B2C25)
val surfaceContainerHighestDark = Color(0xFF36372F)